spring:
  application:
    name: hr-payroll

server:
  port: ${port:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


resilience4j.circuitbreaker:
  instances:
    myService:
      timeoutDuration: 60000

ribbon:
  ReadTimeout: 20000 # Tempo limite para leitura (em milissegundos)
  ConnectTimeout: 10000 # Tempo limite para conexão (em milissegundos)