server:
  port: 8765
spring:
  application:
    name: hr-api-gateway

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true

---

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true