spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victoroliveirajv/ms-course-configs
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}

server:
  port: 8888
